insert into Screen (name, username, format_name, format_rows, format_cols, format_subs, comments) values
("c3_1", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Peggy: Low MW, diverse buffers, pH range and salts."),
("c3_2", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Peggy: Low-Mid MW, diverse buffers, pH range and salts."),
("c3_3", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Peggy: 3350 and 4000, diverse buffers, pH range and salts."),
("c3_4", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Peggy: Mid-High MW, diverse buffers, pH range and salts."),
("c3_5", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Salty: ammonium sulfate, other sulfates, citrates"),
("c3_6", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Salty: various phosphates, chlorides, acetates, formates, tartrates"),
("c3_7", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Organics: MPD, 'small' branched polymers, hexanediol."),
("c3_8", "c3@csiro.au", "Screen96Well", 8, 12, 0, "Organics: Alcohols."),
("HELIX_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Designed for nucleic acids - modified from the HELIX screen sold by Molecular Dimensions"),
("Index_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Hampton's Index screen, made up in C3."),
("JCSG+_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Emerald Biosciences JCSG+, made up by C3."),
("LCP_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "C3's take on the LCP screen designed by Martin Caffrey and published in 2015, now with buffered tricine in well E12"),
("Lysozyme QA Screen", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Four conditions that grow lysozyme crystals with different morphology."),
("MemFac_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Hampton's MemFac screen, made up by C3."),
("MemGold2_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Molecular Dimensions MemGold2 screen, made up by C3. Tweaked to be only 80 stocks."),
("MemGold_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Molecular Dimensions MemGold screen, made up by C3, and modified to have only 80 stocks"),
("Morpheus_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Molecular Dimensions Morpheus screen, made up by C3."),
("PACT_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Qiagen's PACT Suite, made up by C3."),
("Paydirt_2", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "None"),
("PI_PI2_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "1-48 is PEG/Ion, 49-96 is PEG/Ion II.  PEG/Ion 2 reagent 43 used to be 20% PEG 3350, 0.02M NiCl2, 0.02M MgCl2, 0.02M FeCl3 - but the ferric chloride made the condition very acidic, and Hampton Research dropped this formulation starting from Lot 209802"),
("ProPlex_C3", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "Based on Molecular Dimensions ProPlex screen, made up by C3."),
("PS gradient - mid range", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "pH and salt gradient: The salt (1.2 - 2.2M) is either ammonium sulfate or sodium malonate, pH ranges from 4 - 10 (one buffer system), and 5.5, 6.5 ,7.5 or 8.5 (distinct buffers)."),
("PS gradient", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "pH and salt gradient: The salt (0.5 - 3.0M) is either ammonium sulfate or sodium malonate, pH ranges from 4 - 10 (one buffer system), and 5.5, 6.5 ,7.5 or 8.5 (distinct buffers)."),
("Shotgun", "c3@csiro.au", "Generic 96 Well", 8, 12, 1, "This is a collection of the 96 most successful commercial conditions as determined by mining the PDB");